# Generated by Django 3.0 on 2019-12-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20191218_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.BinaryField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='headline',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
