# Generated by Django 3.0 on 2019-12-18 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_product_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
