# Generated by Django 3.0 on 2019-12-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20191218_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=700),
        ),
        migrations.AlterField(
            model_name='product',
            name='headline',
            field=models.CharField(max_length=300),
        ),
    ]
