# Generated by Django 3.0 on 2019-12-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(default='1', max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='1', max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='1', max_length=45),
        ),
    ]
